/*
 * starter core - test-mysql-client.c
 *
 * Authored by Gemini AI (Google) as a collaborative engineering effort.
 * * CRITICAL LIMITATION: Only this specific file is dedicated to the public 
 * domain under the terms of the Creative Commons Zero (CC0 1.0 Universal) license. 
 * This dedication does NOT apply to any other files, source code, or architecture 
 * within the STARTER framework, which remain strictly protected.
 *
 * You can copy, modify, distribute and perform the work in this file, even for 
 * commercial purposes, all without asking permission.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
 */

#define _GNU_SOURCE

#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>

#include <starter/mysql-client.h>
#include <starter/input.h>
#include <starter/output.h>
#include <starter/error.h>

/* Function pointers to control the preloaded mock state without compile-time linking */
static void (*set_query_failure) (gboolean) = NULL;
static void (*set_row_value) (const gchar *) = NULL;
static const gchar *(*get_last_query) (void) = NULL;

typedef struct {
  STMYSQLClient *client;
} TestFixture;

static void
fixture_setup (TestFixture *fixture, gconstpointer user_data)
{
  /* Resolve the control API hooks inside the preloaded LD_PRELOAD shared object matrix */
  set_query_failure = dlsym (RTLD_DEFAULT, "mock_mysql_set_query_failure");
  set_row_value = dlsym (RTLD_DEFAULT, "mock_mysql_set_row_value");
  get_last_query = dlsym (RTLD_DEFAULT, "mock_mysql_get_last_query");

  /* Reset mock execution boundaries before entering the pipeline */
  if (set_query_failure) 
    set_query_failure (FALSE);
    
  if (set_row_value) 
    set_row_value (NULL);

  fixture->client = st_mysql_client_new ("ArmageddonNode", "127.0.0.1", 3306, "root", "secret");
  g_assert_nonnull (fixture->client);
}

static void
fixture_teardown (TestFixture *fixture, gconstpointer user_data)
{
  g_clear_object (&fixture->client);
}

/* --- VALIDATION TESTS --- */

/* Test 1: Verify Label storage execution and validate generated SQL statements string formatting */
static void
test_mock_store_input_label (TestFixture *fixture, gconstpointer user_data)
{
  GError *error = NULL;
  STInput *input = st_input_new ("InjectedHW", "Hardware Monitor Component", ST_UNIT_NULL, 0.0, 10.0, 1.0, 1.0, 0);
  g_assert_nonnull (input);

  gboolean success = st_mysql_client_store_input_label (fixture->client, input, &error);
  g_assert_true (success);
  g_assert_no_error (error);

  /* Extract the query stored inside our mock layer to inspect dynamic code compliance */
  const gchar *last_query = get_last_query ? get_last_query () : NULL;
  g_assert_nonnull (last_query);
  
  /* Validate string structural characteristics generated by the client wrapper */
  g_assert_cmpint (last_query[0], ==, 'I'); // Validate INSERT initiation
  g_assert_nonnull (strstr (last_query, "InjectedHW"));
  g_assert_nonnull (strstr (last_query, "ON DUPLICATE KEY UPDATE"));

  g_object_unref (input);
}

/* Test 2: Verify system recovery pipelines and GError translation on query execution aborts */
static void
test_mock_query_failure_handling (TestFixture *fixture, gconstpointer user_data)
{
  GError *error = NULL;
  STInput *input = st_input_new ("FailHW", "Hardware Fail Component", ST_UNIT_NULL, 0.0, 10.0, 1.0, 1.0, 0);
  g_assert_nonnull (input);

  /* Instruct the mock engine to drop the incoming database connection channel transaction */
  if (set_query_failure) 
    set_query_failure (TRUE);

  gboolean success = st_mysql_client_store_input_label (fixture->client, input, &error);
  g_assert_false (success);
  g_assert_nonnull (error);
  g_assert_cmpstr (error->message, ==, "Simulated Mock Database Engine Error Exception");

  g_clear_error (&error);
  g_object_unref (input);
}

/* Test 3: Verify SELECT response extraction matrices parsing double fields out from mock records */
static void
test_mock_get_last_history_value (TestFixture *fixture, gconstpointer user_data)
{
  GError *error = NULL;
  gdouble anticipated_value = 85.45;

  /* Instruct our fake client matrix to map out a single row entry matching our schema expectations */
  if (set_row_value) 
    set_row_value ("85.450000");

  gdouble value = st_mysql_client_get_last_history_value (fixture->client, "InjectedHW", &error);
  g_assert_no_error (error);
  g_assert_cmpfloat_with_epsilon (value, anticipated_value, 0.001);

  const gchar *last_query = get_last_query ? get_last_query () : NULL;
  g_assert_nonnull (last_query);
  g_assert_nonnull (strstr (last_query, "SELECT value FROM"));
}

int
main (int argc, char *argv[])
{
  g_test_init (&argc, &argv, NULL);

  g_test_add ("/libstarter-core/mock-mysql/store-input-label",
              TestFixture, NULL,
              fixture_setup, test_mock_store_input_label, fixture_teardown);

  g_test_add ("/libstarter-core/mock-mysql/query-failure",
              TestFixture, NULL,
              fixture_setup, test_mock_query_failure_handling, fixture_teardown);

  g_test_add ("/libstarter-core/mock-mysql/get-last-history",
              TestFixture, NULL,
              fixture_setup, test_mock_get_last_history_value, fixture_teardown);

  return g_test_run ();
}

